### PR TITLE
Request to add Minibars.js

### PR DESCRIPTION
**Pull request by Udo**
I know you don't like templating libraries, but this is a drop-in replacement for a huge mainstream library called Handlebars, so I'm hoping you're willing to consider it.

### CODE REVIEW

**Comment by sbrl** [comment]
It would be helpful if, in your commit, you didn't update data-min.js or data.js I think. This makes it easier when the project maintainers are merging multiple requests.

**Comment by Udo** [comment]
@sbrl they explicitly instruct people to edit data.js when they say "Fork this site on GitHub, add your framework to "data.js" and submit a pull request." - I guess data-min.js has been modified automatically. But if you're not allowed to modify data.js, what's the basis for creating a pull request in the first place? I'm confused.

If this means Minibars will get included in the end, I'll try again and be careful to leave data-min.js as it is. Just let me know.

**Comment by SimonWaldherr** [comment]
@Udo on each pull request we have to check the following things:
* have no dependencies
* something useful, not be just a demo
* MIT/BSD-license or similar permissive license
* < 5k when minified and gzipped
* Source file must be available for download and not change name across releases
* unminified, hand written code preferred 

than we ```git checkout``` + ```git pull``` the branch, ```git merge``` it to our master //*repeat this step for every pr since last update day*

if someone change data-min.js or make other "*not git mergeable*" changes (e.g. reorder all entrys in data.js, replaces all spaces with tabs, ...) we have to fix these conflicts, this is time intensive extra work.

more information about *git conflicts*:
* [@git-scm.com](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)
* [@githowto.com](http://githowto.com/resolving_conflicts)
* [@help.github.com](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/)

i recently added a [CONTRIBUTING.md](https://github.com/madrobby/microjs.com/blob/master/CONTRIBUTING.md)-file with informations for contributors which is displayed every time someone creates a Pull Request or Issue.

**Comment by sbrl** [comment]
Perhaps we should change the readme to reflect that pull requesters should edit `data-min.js`? I can create a pull request if you want.

**Comment by Udo** [comment]
@SimonWaldherr I think you misunderstood me, I know about all of these. The problem was in my opinion that I checked in a modified data-min.js, which - let me stress this - I did not manually edit. 

Slightly offtopic and probably unwanted advice, but my suggestion to you guys would be to exclude data-min.js from the repo alltogether since it's purely a build product.

**Comment by sbrl** [comment]
@Udo Good idea. excluding `data-min.js` sounds like a good idea, but it might be a good idea to check to make sure that github pages doesn't use it first. If it does perhaps there could be a separate verification script that deletes it automatically / doesn't generate it at all?

**Comment by SimonWaldherr** [comment]
@Udo if you run build.js to test your changes, it automatically generate/updates the atom.xml and data-min.js files, if you than accidentally commit all changes, this is what happens.

@sbrl i'am not sure if i understand your hint, i think there is a little misunderstanding about the data-min.js file. It's not only a minified version of data.js, it also contains needed data about lib size, tweet count, star count and watch count. It is also filtered via the rules in config.js.

I think the best method to prevent such errors in the future is adding data-min.js to the .gitignore file.

**Comment by Udo** [comment]
@SimonWaldherr exactly. I think we all know *how* it happened, and for my part I'm sorry to have caused additional work, but: yes, adding those build products to .gitignore is what I would have done in your place too. Not sure what your Github pages deployment process looks like, but you could just run build.js on a checked-out version before uploading the whole thing, right? If it's totally automated, this could be done from a cron job or a CI server.

**Comment by SimonWaldherr** [comment]
@Udo I am a big fan of CI (e.g. [my extremely tested go repo](https://github.com/SimonWaldherr/golibs)) but the deployment of microjs is mostly handwork, because mostly i have to check some error messages.
An other method to automate the deployment would be a pre-commit hook, but ... same problem as before ...

i am thinking for quite some time about adding CI tests ...
... but until now i hadn't the time for it
... and it's not always easy to check all the above noticed things (e.g. the Github API can't deliver license infos for all repos)

**Comment by audiolion** [comment]
closing per inactivity

**Pull request closed without merging**
