### PR TITLE
Add EQCSS to microjs.com

### PR DESCRIPTION
**Pull request by tomhodgins**
Hi! I noticed that there weren't any element queries / container queries plugins on microjs.com so I thought I'd fix that 👍

### CODE REVIEW

**Comment by audiolion** [comment]
They are still there 😛

**Comment by tomhodgins** [comment]
Hi @audiolion! Thanks for having a peek at this PR! I've just pushed a commit removing the auto-generated files and updating the description/tags of the library. Let me know if you need anything else :D

https://github.com/microjs/microjs.com/pull/840/commits/88eddbbafb56cd860aa085cd8550b973ae682bdc

**Comment by tomhodgins** [comment]
I can't see the files in my repository on disk, or my fork here on Github, it appears like they're deleted to me :/

**Comment by audiolion** [comment]
So what I meant by remove was to not actually `git rm` them, but remove your changes to them, perhaps it would be easiest for you to close this PR and refork the repository and only modify `data.js`

**Pull request closed without merging**
