### PR TITLE
Added FrontExpress library

### PR DESCRIPTION
**Pull request by camelaissani**

### CODE REVIEW

**Comment by camelaissani** [comment]
@audiolion It seems that the website has not been updated, doesn't it? My library is not visible yet.

**Comment by audiolion** [comment]
i'll look into it

**Comment by camelaissani** [comment]
@audiolion sorry to bother you again with that, but my lib has not been published yet on your web site :disappointed:

**Comment by SimonWaldherr** [comment]
@camelaissani it's online now 👍

**Comment by camelaissani** [comment]
Thanks so much :ok_hand: :tada:

**Comment by SimonWaldherr** [comment]
I'm glad if I could help
thanks for contributing

**Pull request merged**
