### PR TITLE
added dom-events-delegation

### PR DESCRIPTION
**Pull request by brunoscopelliti**
Hi

dom-events-delegation is a JavaScript (delegation) event micro library (more info here http://brunoscopelliti.github.io/dom-events/).

I would  appreciate if you'll consider to add it to the micro.js collection.

Thank you.

### CODE REVIEW

**Comment by sbrl** [comment]
Could you point the `source` url at your unminified code please?

**Comment by brunoscopelliti** [comment]
Hi @sbrl ,
thank you for coming back to me...
i've just pushed the editing you suggested...

let me know if is there anything else i can do to help.
thank you

**Comment by sbrl** [comment]
@brunoscopelliti Thanks! Could you squash your commits into a single commit too please?

**Comment by brunoscopelliti** [comment]
Hi @sbrl 

This is something I've never done before. (Really learning Git is on my todo list for too long.)

I searched on google... and I found I've to do a rebase.

I read about rebase [here](https://ariejan.net/2011/07/05/git-squash-your-latests-commits-into-one/), and several other blog post.

So I executed the commands:

```
git rebase -i HEAD~2
```

I edited the commits history as follows:

```
p fa92d51 added dom-events-delegation
f bafb404 point the source url at the unminified code
```

Save, quit.

```
Brunos-iMac:microjs.com brunoscopelliti$ git rebase -i HEAD~2
Successfully rebased and updated refs/heads/master.
```

The result is that history didn't change at all, but the new file is created.

If I try:

```
git push origin -f
```

I get the "Everything up-to-date" message.

What have i missed?
Any help will be appreciated.

**Comment by sbrl** [comment]
You want to change the `f` to `squash`, and then once the rebase is is complete, perform a `git push origin --force`. If that doesn't work, I'll take a look in my branch instead.

**Comment by brunoscopelliti** [comment]
I've already tried with `squash` (or the less verbose `s`).
I get the same result...

**Comment by sbrl** [comment]
@brunoscopelliti That should have worked. I think git is not working correcting - I'll take a look in my branch when I add it to my next commit bundle.

Thanks for trying though!

**Comment by brunoscopelliti** [comment]
You're welcome.

**Comment by pineapplemachine** [comment]
Closed because changes were requested and no action was taken. Please feel welcome to create a new PR after resolving merge conflicts! You should place your added entry in `data.js` randomly and not at the very bottom, since this will help to prevent you from encountering another merge conflict.

Sorry this has been such a drawn-out process for you...

**Pull request closed without merging**
