### PR TITLE
Update data.js

### PR DESCRIPTION
**Pull request by lmettini**
Hi guys, just want to add my data observer library

### CODE REVIEW

**Comment by lmettini** [comment]
Any news about this, is it going to be added?

**Comment by lmettini** [comment]
The license was added, don't see the conflict that you mentioned

**Comment by audiolion** [comment]
Move your data.js wntry to somewhere in the middle of the file to resolve the conflict

**Comment by audiolion** [comment]
Do `git pull --rebase upstream master` to rebase your file and fix conflicts

**Comment by lmettini** [comment]
Just created a new pull request, don't have the clone repo in this machine
https://github.com/microjs/microjs.com/pull/905


Cheers

**Pull request closed without merging**
