### PR TITLE
Subscript micro-language

### PR DESCRIPTION
**Pull request by dy**
Subscript is extensible micro-language with syntax subset common for C++/JS/Java/Rust/Go/Python.
Useful for template evaluation, expression evaluations, custom DSL etc.

### CODE REVIEW

**Comment by dy** [comment]
@pineapplemachine

**Review by pineapplemachine — CHANGES_REQUESTED** [review]
@dy, your `url` and `source` links both seem to be broken.

https://github.com/spectjs/subscript gives me a 404. (Is your repository set to private?)

https://unpkg.com/subscript@1.0.2/subscript.js says "Cannot find package subscript@1.0.2".

**Comment by dy** [comment]
Hey @pineapplemachine, just made it public.

**Comment by pineapplemachine** [comment]
Sorry, another change is needed. You do not have a license text file in your repository, and your `package.json` lists license as `??`. Unless you provide a license for your code, it is legally questionable for anybody else to use or reproduce it. From the microjs repository readme, contributions must use a permissive open-source license:

> Must be MIT/BSD-license or similar permissive license

**Comment by dy** [comment]
Thanks! Added license.

**Review by pineapplemachine — APPROVED** [review]
Ok, looks good. Thank you

**Pull request merged**
