### PR TITLE
Add XPopUp

### PR DESCRIPTION
**Pull request by reduardo7**

### CODE REVIEW

**Comment by pineapplemachine** [comment]
Thanks for updating your PR!

There is one more problem, though - before your addition can be accepted you will need to add a license to your repository. Here is a good SO post showing how to do just that: https://stackoverflow.com/a/37895659/3478907

The MIT license is a good choice and one that is acceptable for including your project in microjs. You can read about the MIT license here: https://github.com/angular/angular.js/blob/master/LICENSE

**Comment by pineapplemachine** [comment]
Looks like there's a conflict after merging https://github.com/microjs/microjs.com/pull/955 - please also fix the merge conflict!

**Comment by reduardo7** [comment]
PR updated

**Comment by pineapplemachine** [comment]
@reduardo7 you still have to add a license to your repository

**Comment by reduardo7** [comment]
@pineapplemachine Done!

**Comment by pineapplemachine** [comment]
Looks good. Thanks for updating!

https://github.com/microjs/microjs.com/pull/830

**Pull request merged**
