### PR TITLE
Add ajaxify.js

### PR DESCRIPTION
**Pull request by marcoroganovic**

### CODE REVIEW

**Comment by audiolion** [comment]
Hey can you remove the atom.xml file? It is automatically generated and not needed

**Comment by audiolion** [comment]
Hey so by remove I mean dont include it in the commit, not to actually delete :P, maybe its easiest to start the PR over and not include data.min.js or atom.xml in your commit. The way you would fix is probably to git reset HEAD^ and git checkout -- atom.xml git checkout -- data.min.js then recommit data.js

**Comment by tunnckoCore** [comment]
Probably better would be that to add these files on `.gitignore` so users won't think.

**Comment by audiolion** [comment]
Agreed to add to `.gitignore`, it was on my TODO when I went through this, though the build is important to make sure your library passes our build tests, e.g. it has recent commits (~1 year), meets zip requirements, uglify's correctly, source is downloadable, and some other checks

**Comment by pineapplemachine** [comment]
I'm closing this PR because it modifies `atom.xml` and `data-min.js`, which are automatically-generated files. (They probably should be gitignored but this is a problem for another day.) Please feel welcome to make a new PR for your package that modifies only `data.js`!

**Pull request closed without merging**
