### PR TITLE
add dom99

### PR DESCRIPTION
**Pull request by GrosSacASac**
> The 'source' attribute must point to a single-file, or an array of files that can be concatenated to form your complete library in a ready-to-use form.

The problem is that it will not work since it uses modules instead of globals, so I linked to the source directory instead.

Otherwise the ready to use file is https://unpkg.com/dom99@21.0.3/built/dom99.es.js

### CODE REVIEW

**Comment by pineapplemachine** [comment]
I would recommend using the ready-to-use file link instead of a source directory. The automated tool won't know what to do with a link to a directory and will exclude your package from the site build process. It _might_ know what to do with an es module.

**Comment by GrosSacASac** [comment]
would this be ok https://unpkg.com/dom99/built/dom99.es.js
without version unpkg redirects to the latest

**Comment by pineapplemachine** [comment]
Looks fine to me but I suggest running it by the build check to find out for sure

**Comment by pineapplemachine** [comment]
I have no problem merging it like that, but whether the build tool will actually include it is another question that I haven't got time to answer right now

**Pull request merged**
